apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
spec:
  serviceRef:
    name: frontend   # route traffic to the frontend service
    port: 80         #service port (Go and chekc this in service.yaml in the "frontend" folder, so that you can understand which PORT)
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:688567281358:targetgroup/expense-dev/bdfb372b6831dc29