apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  namespace: expense
  # labels of deployemnt resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: blue
spec:
  replicas: 1
  selector:
  # As we have many pods ,we should give what labels the deployment to match
    matchLabels:
      app: backend
      tier: backend
      project: expense
      version: blue
  # pod template
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        version: blue
    spec:
      containers:
      - name: expense
        image: jayakrishna1993/backend:3.0.0
        envFrom:
        - configMapRef:
            name: backend


